### ISSUE TITLE
Use new filter "edd_price_option_output " in EDD 2.8 instead of "edd_purchase_link_top"

### ISSUE THREAD

**Issue by mintplugins** [JeroenSormani/EDD-Sale-Price#15]
Easy Digital Downloads 2.8 will add a new filter called "edd_price_option_output" which allows you to filter the output of each variable price. This removes the need for replacing the output edd_purchase_link_top. This will resolve a few issues that have arisen like microdata not being present and filtered-in class names not being present. 

Will also resolve https://github.com/JeroenSormani/EDD-Sale-Price/issues/12

I'll submit a Pull Request shortly. Note that this should not be merged until after EDD 2.8 is released.

**Comment by mintplugins** [comment]
@JeroenSormani

**Comment by JeroenSormani** [comment]
Thanks @mintplugins !

I've also just synced the change you did in EDD Core here: https://github.com/JeroenSormani/EDD-Sale-Price/pull/18
I suppose that may fix things for this topic: https://wordpress.org/support/topic/not-compatible-with-edd-all-access-extension/ ?
To make it work pre 2.8, thoughts on it?

**Comment by mintplugins** [comment]
Hey @JeroenSormani.

That function you are [adding the classes to](https://github.com/JeroenSormani/EDD-Sale-Price/pull/18) is completely removed in the change I am adding here so there's actually no need for it. 

2.8 will be coming out within the next couple weeks or so, so I don't think we'll have to fix it pre 2.8. Customer can just upgrade to EDD 2.8 if they have issues.

**Comment by JeroenSormani** [comment]
Merged the PR, thanks again @mintplugins!
