### ISSUE TITLE
Add regular price with strikethrough on the button

### ISSUE THREAD

**Issue by growdev** [JeroenSormani/EDD-Sale-Price#5]
This sale price:
![edit download edd test wordpress-1](https://cloud.githubusercontent.com/assets/290886/6829505/eae1152e-d2e1-11e4-86e7-e0b9c183580c.jpg)

Only shows the sale price on the button:
![small download edd test](https://cloud.githubusercontent.com/assets/290886/6829519/fe25b2f2-d2e1-11e4-8832-c12516922886.jpg)

Request is to have it show the Regular Price (strikethrough) followed by the Sale Price

ref: https://wordpress.org/support/topic/no-regular-price-at-the-button

**Comment by JeroenSormani** [comment]
See https://wordpress.org/support/topic/no-regular-price-at-the-button?replies=4#post-6989497
