### ISSUE TITLE
Regular price isn't showing correctly if variable prices

### ISSUE THREAD

**Issue by fxbenard** [JeroenSormani/EDD-Sale-Price#6]
The fist price is picked not the right one on the checkout page

![2015-05-19_13-59-24](https://cloud.githubusercontent.com/assets/802114/7702361/e6172456-fe2f-11e4-96b0-8b041b5320a0.jpg)
![2015-05-19_13-59-58](https://cloud.githubusercontent.com/assets/802114/7702362/e61bd122-fe2f-11e4-843d-a0614bdd88d7.jpg)

**Comment by JeroenSormani** [comment]
Thank for catching that!

I'll look into this soon.
